cursor #dae5e3
cursor_text_color #b8cac9

foreground            #dae5e3
background            #0c1515
selection_foreground  #063543
selection_background  #a5cdde
url_color             #ffb77a

color0   #0c1515
color1   #ff746c
color2   #90ff7a
color3   #ffe56c
color4   #f2a05a
color5   #763805
color6   #ffb77a
color7   #fff6ef
color8   #a59e98
color9   #ffa09b
color10  #b1ffa1
color11  #ffeea1
color12  #ffc18d
color13  #ffcca1
color14  #ffdec3
color15  #fffbf8
