################################
## ~/.config/kitty/kitty.conf ##
## ×Joda™ ######################
################################

include dank-theme.conf
include dank-tabs.conf

confirm_os_window_close 0
allow_remote_control yes
mouse_hide_wait 3.0
map f5 load_config_file

window_padding_width 2

cursor none
cursor_shape underline
cursor_shape_unfocused hollow
cursor_blink_interval 0.50 ease-in-out
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.2 0.8
cursor_trail_start_threshold 2
cursor_trail_color #8c63aa

map ctrl+o scroll_to_prompt -1
map ctrl+i scroll_to_prompt 1
map ctrl+w close_window
map ctrl+enter new_window
map ctrl+[ next_window
map ctrl+] previous_window
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window top
map alt+down neighboring_window bottom
map ctrl+shift+l next_layout
map ctrl+` move_window_to_top
map ctrl+shift+a copy_ansi_to_clipboard
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

map ctrl+, set_tab_title 
map ctrl+. launch --type=tab --location=neighbor
map ctrl+/ launch --type=tab
map alt+tab next_tab
map shift+alt+tab previous_tab
map alt+` goto_tab -1
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

## for tmux ##
# # Reset existing mappings
# map ctrl+alt+tab        next_tab
# map ctrl+alt+shift+tab previous_tab
# # Send Ctrl Tab and Ctrl + Shift + Tab for tmux navigation
# map ctrl+tab send_text all \x1b[27;5;9~
# map ctrl+shift+tab send_text all \x1b[27;6;9~
# tab_bar_min_tabs 2

undercurl_style thin-sparse
font_size 11.0
disable_ligatures cursor
# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

